version: 2

sources:
  - name: eco_finance
    schema: dataset_eco_finance
    tables:
      - name: co2_per_capita
        identifier: per-capita-co-emissions-cleaned
      - name: SP500_ESG_2022_700_stocks
        identifier: SP500_2022_Compo_ESG_scoring_700_stocks
      - name: GHG_Emissions
        identifier: Green_House_Emissions_Yearly_Clean 
      - name: cata_nature
        identifier: cata_nature
      - name: company_emissions_overview
        identifier: eco_finance_co2_final_clean
      - name: all_data_stock
        identifier: all_data_stock
      - name: Exxon_Mobil_Full_Stock
        identifier: Exxon_Mobil_Full_Stock
      - name: Nextera_Full_Stock
        identifier: Nextera_Full_Stock
   #   - name: All_stocks_history
    #    identifier: all_data_stock
      - name: nextera_emissions
        identifier: nextera_emissions
      - name: nextera_generation_mwh
        identifier: nextera_generation_mwh
      - name: nextera_profile_financials
        identifier: nextera_profile_financials
      - name: nextera_waste
        identifier: nextera_waste
      - name: nextera_water_conso
        identifier: nextera_water
      - name: big_co2_esg_company_
        identifier: stg_eco_finance_esg_co2
      
        
         