version: 2

sources:
  - name: eco_finance
    schema: dataset_eco_finance
    tables:
      - name: co2_per_capita
        identifier: per-capita-co-emissions-cleaned
      - name: SP500_ESG_2022_700_stocks
        identifier: SP500_2022_Compo_ESG_scoring_700_stocks
      - name: GHG_Emissions
        identifier: Green_House_Emissions_Yearly_Clean 
      - name: cata_nature
        identifier: cata_nature
      - name: company_emissions_overview
        identifier: company_emissions_overview